diff a/drivers/video/msm/mdss/Makefile b/drivers/video/msm/mdss/Makefile	(rejected hunks)
@@ -74,5 +74,7 @@ obj-$(CONFIG_FB_MSM_QPIC_ILI_QVGA_PANEL) += qpic_panel_ili_qvga.o
 
 obj-$(CONFIG_FB_MSM_MDSS) += mdss_fb.o mdss_util.o
 obj-$(CONFIG_COMPAT) += mdss_compat_utils.o
-
 obj-$(CONFIG_FB_MSM_MDSS) += mdss_livedisplay.o
+obj-$(CONFIG_FB_MSM_MDSS_KCAL_CTRL) += mdss_mdp_kcal_ctrl.o
+obj-$(CONFIG_FB_MSM_MDSS) += lcd_notify.o
+
